include: package:lint/analysis_options.yaml

linter:
  rules:
    - lines_longer_than_80_chars
    - prefer_adjacent_string_concatenation
    - avoid_catches_without_on_clauses

analyzer:
  errors:
    avoid_print: ignore

  strong-mode:
    implicit-casts: false

  exclude:
    # ignore warnings in files from json_serializable, built_value and most generators
    - "**/*.g.dart"