name: muslim_prayer_times
description: A muslim prayer times app that displays organised prayer times and qibla directions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: "2.10.5"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  get: ^3.24.0

  introduction_screen: ^1.0.9

  location: ^3.2.4
  location_permissions: ^3.0.0+1

  google_maps_flutter: ^1.1.1

  geocode: ^0.1.3

  flag: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
  hive_generator: ^0.8.2
  build_runner: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/kaaba_logo_brown.png
    - assets/images/clock.png
    - assets/images/compass.png
    - assets/images/loading.png
    - assets/images/ui-element-150.png
    - assets/images/map.png
    - assets/images/location-pin2.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf