name: muslim_prayer_times
description: A muslim prayer times app that displays organised prayer times and qibla directions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: "2.12.2"

dependencies:
  cupertino_icons: ^1.0.2
  flag: ^5.0.0-nullsafety
  flutter:
    sdk: flutter
  geocode: ^1.0.1
  get: ^4.1.4
  google_maps_flutter: ^2.0.3
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  introduction_screen: ^2.1.0
  location: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  lint: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/kaaba_logo_brown.png
    - assets/images/clock.png
    - assets/images/compass.png
    - assets/images/loading.png
    - assets/images/ui-element-150.png
    - assets/images/map.png
    - assets/images/location-pin2.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf